<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rs" nsURI="http://org.rs" nsPrefix="org.rs">
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Preference" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Profile" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CollaborativeFiltering" eSuperTypes="#//FilteringRS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="_isUserBased" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="_neighbors" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" upperBound="-1" eType="#//UserItemMatrix"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserItemRow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="_user" lowerBound="1" eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="_item" lowerBound="1" eType="#//Item"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserItemMatrix">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" upperBound="-1" eType="#//UserItemRow"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentBased" eSuperTypes="#//FilteringRS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentBasedPreference"
        upperBound="-1" eType="#//ContentBasedPreference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentBasedPreference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="_user" lowerBound="1" eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="_prefs" upperBound="-1"
        eType="#//Preference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HybridBased" eSuperTypes="#//FilteringRS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="_cfComponent" eType="#//CollaborativeFiltering"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="_cbComponent" eType="#//ContentBased"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FilteringRS" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="similarityFunction" eType="#//SimilarityFunction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SimilarityFunction">
    <eLiterals name="COSINE"/>
    <eLiterals name="PEARSON" value="1"/>
    <eLiterals name="EUCLIDEAN" value="2"/>
    <eLiterals name="HAVERSINE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Algorithm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filteringRS" eType="#//FilteringRS"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
